# Generated by Django 5.1.1 on 2024-10-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
