# Generated by Django 5.1.1 on 2024-10-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_cost',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
