# Generated by Django 5.1.1 on 2025-04-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
