# Generated by Django 5.2 on 2025-12-13 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_purchase_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.store'),
        ),
    ]
